index:
    path: /
    controller: App\Controller\Home::landing
authorize:
    path: /authorize
    controller: App\Controller\Home::authorize
access:
    path: /access
    controller: App\Controller\Home::access